let rawData=[],filteredData=[],typeChart=null,scatterChart=null,weekendChart=null,map=null,markersLayer=null,currentFileName='',currentEncoding='';
const $=id=>document.getElementById(id);const nf=new Intl.NumberFormat('ko-KR');
const REQUIRED=['개방시설명','개방시설유형구분','유료사용여부','사용료','수용가능인원수','면적','주말운영시작시각','주말운영종료시각','위도','경도'];

$('csvFile').addEventListener('change',e=>{if(e.target.files[0])loadFile(e.target.files[0]);});
['searchInput','typeFilter','paidFilter','weekendFilter'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',applyFilters));
const dz=$('dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('dragover')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)loadFile(f)});

async function loadFile(file){
  currentFileName=file.name;$('loadStatus').className='load-status';$('loadStatus').textContent='파일을 읽는 중입니다...';
  try{
    const buffer=await file.arrayBuffer();
    let text='';
    try{text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);currentEncoding='UTF-8';}
    catch(e){text=new TextDecoder('euc-kr').decode(buffer);currentEncoding='CP949 / EUC-KR 계열';}
    text=text.replace(/^\uFEFF/,'');
    Papa.parse(text,{header:true,skipEmptyLines:'greedy',transformHeader:h=>normalizeHeader(h),complete:res=>finishLoad(res),error:err=>showError(err.message)});
  }catch(err){showError('파일을 읽을 수 없습니다: '+err.message)}
}
function finishLoad(results){
  if(!results.data?.length){showError('데이터 행을 찾지 못했습니다.');return;}
  const fields=(results.meta.fields||[]).map(normalizeHeader);
  const missing=REQUIRED.filter(x=>!fields.includes(x));
  rawData=results.data.map(normalizeRow).filter(d=>d.__name||d.__agency||d.__address);filteredData=[...rawData];
  if(!rawData.length){showError('시설 데이터를 찾지 못했습니다. CSV 구조를 확인해 주세요.');return;}
  $('loadStatus').textContent=`${currentFileName} · ${currentEncoding} · ${nf.format(rawData.length)}건 분석 완료${missing.length?' · 일부 컬럼 미인식':''}`;
  $('emptyState').classList.add('hidden');$('dashboard').classList.remove('hidden');
  $('badgeFile').textContent='파일 '+currentFileName;$('badgeEncoding').textContent='인코딩 '+currentEncoding;$('badgeRows').textContent='데이터 '+nf.format(rawData.length)+'건';
  const dates=rawData.map(d=>d.__date).filter(Boolean).sort();$('badgeDate').textContent='기준일 '+(dates.at(-1)||'-');
  buildTypeFilter();renderAll(fields);setTimeout(()=>map&&map.invalidateSize(),150);
}
function showError(msg){$('loadStatus').className='load-status error';$('loadStatus').textContent=msg;}
function normalizeHeader(h){return String(h??'').replace(/^\uFEFF/,'').replace(/[\u00A0\u200B]/g,'').trim();}
function clean(v){return v==null?'':String(v).replace(/^\uFEFF/,'').trim();}
function num(v){if(v==null||v==='')return NaN;const n=Number(String(v).replace(/,/g,'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:NaN;}
function parseTime(t){const m=clean(t).match(/(\d{1,2})\s*:\s*(\d{1,2})/);return m?Number(m[1])+Number(m[2])/60:null;}
function hours(s,e){const a=parseTime(s),b=parseTime(e);return a!=null&&b!=null?Math.max(0,b-a):NaN;}
function normalizeRow(r){
  const fee=num(r['사용료']),cap=num(r['수용가능인원수']),area=num(r['면적']),useHours=num(r['사용기준시간']);
  const ws=clean(r['주말운영시작시각']),we=clean(r['주말운영종료시각']);
  return {...r,__name:clean(r['개방시설명']),__type:clean(r['개방시설유형구분'])||'미분류',__paid:clean(r['유료사용여부']).toUpperCase(),__fee:fee,__cap:cap,__area:area,__useHours:useHours,__hourly:(Number.isFinite(fee)&&fee>0&&Number.isFinite(useHours)&&useHours>0)?fee/useHours:NaN,__weekdayStart:clean(r['평일운영시작시각']),__weekdayEnd:clean(r['평일운영종료시각']),__weekendStart:ws,__weekendEnd:we,__weekend:(ws&&we)?'Y':'N',__address:clean(r['소재지도로명주소'])||clean(r['소재지지번주소']),__agency:clean(r['관리기관명']),__phone:clean(r['사용안내전화번호']),__lat:num(r['위도']),__lng:num(r['경도']),__date:clean(r['데이터기준일자'])};
}
function valid(a){return a.filter(Number.isFinite)}function avg(a){const x=valid(a);return x.length?x.reduce((s,v)=>s+v,0)/x.length:NaN}function median(a){const x=valid(a).sort((a,b)=>a-b);if(!x.length)return NaN;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}function pct(a,b){return b?a/b*100:0}function fmt(v,digits=0){return Number.isFinite(v)?nf.format(Number(v.toFixed(digits))):'-'}
function group(data,key){return data.reduce((o,d)=>{const k=d[key]||'미분류';o[k]=(o[k]||0)+1;return o},{})}
function renderAll(fields){renderKpis();renderInsights();renderQuality(fields);renderCharts();renderRanks();renderMap(rawData);renderTable(filteredData)}
function renderKpis(){const total=rawData.length,paid=rawData.filter(d=>d.__paid==='Y').length,week=rawData.filter(d=>d.__weekend==='Y').length;$('kpiTotal').textContent=nf.format(total);$('kpiPaid').textContent=pct(paid,total).toFixed(1)+'%';$('kpiCapacity').textContent=fmt(avg(rawData.map(d=>d.__cap)))+'명';$('kpiFee').textContent=fmt(avg(rawData.map(d=>d.__fee)))+'원';$('kpiWeekend').textContent=nf.format(week);$('kpiArea').textContent=fmt(median(rawData.map(d=>d.__area)))+'㎡';}
function renderInsights(){const total=rawData.length,paid=rawData.filter(d=>d.__paid==='Y').length,free=rawData.filter(d=>d.__paid==='N').length,week=rawData.filter(d=>d.__weekend==='Y').length,types=group(rawData,'__type'),top=Object.entries(types).sort((a,b)=>b[1]-a[1])[0]||['-',0],capVals=valid(rawData.map(d=>d.__cap)),feeVals=valid(rawData.map(d=>d.__fee));$('overviewInsight').innerHTML=`총 <strong>${nf.format(total)}개</strong> 시설이 등록되어 있습니다. 가장 많은 유형은 <strong>${esc(top[0])}</strong>으로 ${nf.format(top[1])}개입니다. 유료 시설은 ${nf.format(paid)}개(${pct(paid,total).toFixed(1)}%), 무료 시설은 ${nf.format(free)}개입니다. 수용인원 값이 있는 ${nf.format(capVals.length)}개 시설의 평균 수용인원은 약 <strong>${fmt(avg(capVals))}명</strong>이며, 사용료가 입력된 ${nf.format(feeVals.length)}개 시설의 평균 사용료는 약 <strong>${fmt(avg(feeVals))}원</strong>입니다.`;$('typeInsight').innerHTML=`시설 유형은 <strong>${Object.keys(types).length}종</strong>입니다. <strong>${esc(top[0])}</strong>이 ${pct(top[1],total).toFixed(1)}%로 가장 큰 비중을 차지합니다. 상위 유형의 비중을 함께 보면 개방시설 공급이 특정 용도에 집중되어 있는지 파악할 수 있습니다.`;const value=[...rawData].filter(d=>Number.isFinite(d.__hourly)&&d.__hourly>0).sort((a,b)=>a.__hourly-b.__hourly)[0];$('costInsight').innerHTML=value?`사용기준시간과 사용료가 모두 입력된 시설을 기준으로 시간당 비용을 계산했습니다. 가장 낮은 시설은 <strong>${esc(value.__name)}</strong>으로 시간당 약 <strong>${fmt(value.__hourly)}원</strong>입니다. 단, 시설 규모와 부대시설이 다르므로 비용만으로 최종 판단하기보다 수용인원과 함께 비교하는 것이 좋습니다.`:'사용기준시간 또는 사용료 값이 부족해 시간당 비용 비교가 어렵습니다.';$('weekendInsight').innerHTML=`주말 운영 시작·종료시각이 모두 입력된 시설은 <strong>${nf.format(week)}개</strong>로 전체의 <strong>${pct(week,total).toFixed(1)}%</strong>입니다. 이 데이터에서는 운영시각이 형식적으로 입력되어 있을 수 있으므로 실제 휴관일과 신청 가능 여부도 함께 확인하는 것이 좋습니다.`;}
function renderQuality(fields){const specs=[['유료사용여부','__paid'],['수용가능인원수','__cap'],['사용료','__fee'],['면적','__area'],['위도·경도','map']];$('qualityGrid').innerHTML=specs.map(([label,key])=>{let cnt=0;if(key==='__paid')cnt=rawData.filter(d=>['Y','N'].includes(d.__paid)).length;else if(key==='map')cnt=rawData.filter(d=>Number.isFinite(d.__lat)&&Number.isFinite(d.__lng)).length;else cnt=rawData.filter(d=>Number.isFinite(d[key])).length;const rate=pct(cnt,rawData.length);return `<div class="quality-item">${esc(label)}<strong class="${rate>=80?'ok':'warn'}">${nf.format(cnt)}건 · ${rate.toFixed(1)}%</strong></div>`}).join('');}
function renderCharts(){const ge=Object.entries(group(rawData,'__type')).sort((a,b)=>b[1]-a[1]).slice(0,12);if(typeChart)typeChart.destroy();typeChart=new Chart($('typeChart'),{type:'bar',data:{labels:ge.map(x=>x[0]),datasets:[{data:ge.map(x=>x[1]),backgroundColor:'rgba(36,92,255,.78)',borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});const pts=rawData.filter(d=>Number.isFinite(d.__cap)&&d.__cap>0&&Number.isFinite(d.__hourly)&&d.__hourly>=0).slice(0,1200);if(scatterChart)scatterChart.destroy();scatterChart=new Chart($('scatterChart'),{type:'scatter',data:{datasets:[{label:'시설',data:pts.map(d=>({x:d.__cap,y:d.__hourly,name:d.__name})),backgroundColor:'rgba(9,146,104,.55)'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:c=>`${c.raw.name}: ${fmt(c.raw.x)}명 / 시간당 ${fmt(c.raw.y)}원`}}},scales:{x:{title:{display:true,text:'수용가능인원수'}},y:{title:{display:true,text:'시간당 사용료(원)'},beginAtZero:true}}}});const yes=rawData.filter(d=>d.__weekend==='Y').length,no=rawData.length-yes;if(weekendChart)weekendChart.destroy();weekendChart=new Chart($('weekendChart'),{type:'doughnut',data:{labels:['주말 운영시각 입력','미입력'],datasets:[{data:[yes,no],backgroundColor:['rgba(36,92,255,.82)','rgba(216,222,234,.9)'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'64%',plugins:{legend:{position:'bottom'}}}})}
function renderRanks(){const a=[...rawData].filter(d=>Number.isFinite(d.__cap)&&d.__cap>0).sort((x,y)=>y.__cap-x.__cap).slice(0,5);$('capacityRank').innerHTML=a.map(d=>`<li><strong>${esc(d.__name)}</strong> — ${fmt(d.__cap)}명</li>`).join('');const b=[...rawData].filter(d=>Number.isFinite(d.__hourly)&&d.__hourly>0).sort((x,y)=>x.__hourly-y.__hourly).slice(0,5);$('valueRank').innerHTML=b.map(d=>`<li><strong>${esc(d.__name)}</strong> — 시간당 ${fmt(d.__hourly)}원</li>`).join('')}
function buildTypeFilter(){const t=[...new Set(rawData.map(d=>d.__type))].sort();$('typeFilter').innerHTML='<option value="">전체 시설유형</option>'+t.map(x=>`<option value="${attr(x)}">${esc(x)}</option>`).join('')}
function applyFilters(){const q=$('searchInput').value.trim().toLowerCase(),type=$('typeFilter').value,paid=$('paidFilter').value,week=$('weekendFilter').value;filteredData=rawData.filter(d=>(!q||`${d.__name} ${d.__address} ${d.__agency}`.toLowerCase().includes(q))&&(!type||d.__type===type)&&(!paid||d.__paid===paid)&&(!week||d.__weekend===week));renderTable(filteredData);renderMap(filteredData)}
function renderTable(data){$('resultCount').textContent=`검색 결과 ${nf.format(data.length)}건 · 화면에는 최대 500건 표시`;$('facilityTableBody').innerHTML=data.slice(0,500).map(d=>`<tr><td>${esc(d.__name||'-')}</td><td>${esc(d.__type)}</td><td>${Number.isFinite(d.__cap)?fmt(d.__cap)+'명':'-'}</td><td>${Number.isFinite(d.__fee)?fmt(d.__fee)+'원':(d.__paid==='N'?'무료':'-')}</td><td>${range(d.__weekdayStart,d.__weekdayEnd)}</td><td>${range(d.__weekendStart,d.__weekendEnd)}</td><td>${esc(d.__address||'-')}</td><td>${esc(d.__phone||'-')}</td></tr>`).join('')}
function renderMap(data){const v=data.filter(d=>Number.isFinite(d.__lat)&&Number.isFinite(d.__lng));if(!map){map=L.map('map').setView([36.4,127.8],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);markersLayer=L.layerGroup().addTo(map)}markersLayer.clearLayers();const bounds=[];v.slice(0,1800).forEach(d=>{const m=L.circleMarker([d.__lat,d.__lng],{radius:Math.max(4,Math.min(11,Math.sqrt(Number.isFinite(d.__cap)?d.__cap:25)/2.8)),weight:1,fillOpacity:.68});m.bindPopup(`<strong>${esc(d.__name)}</strong><br>${esc(d.__type)}<br>수용: ${Number.isFinite(d.__cap)?fmt(d.__cap)+'명':'-'}<br>사용료: ${Number.isFinite(d.__fee)?fmt(d.__fee)+'원':(d.__paid==='N'?'무료':'-')}<br>${esc(d.__address)}`);m.addTo(markersLayer);bounds.push([d.__lat,d.__lng])});if(bounds.length)map.fitBounds(bounds,{padding:[25,25],maxZoom:12});}
function range(s,e){return s&&e?`${esc(s)} ~ ${esc(e)}`:'-'}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function attr(v){return esc(v)}
